### ISSUE TITLE
Release conda package

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-memory-profiler#32]
I am trying to build a conda package. Up to now I use conda-forge for this, following more or less the procedure described in https://github.com/spyder-ide/spyder-unittest/wiki/Release . This worked well before, but this time the conda-forge package https://github.com/conda-forge/spyder-memory-profiler-feedstock , which I copied to the `spyder-ide` channel, does not want to be installed in a vanilla conda environment:

```
$ conda install -c spyder-ide spyder-memory-profiler=0.2.1
[...]
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - spyder-memory-profiler=0.2.1 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7
```

A Python 3.7 variant of the conda package does exist in the `spyder-ide` channel:

```
$ conda search -c spyder-ide spyder-memory-profiler --info
[...]
spyder-memory-profiler 0.2.1 py37hc8dfbb8_0
-------------------------------------------
file name   : spyder-memory-profiler-0.2.1-py37hc8dfbb8_0.tar.bz2
name        : spyder-memory-profiler
version     : 0.2.1
build       : py37hc8dfbb8_0
build number: 0
size        : 29 KB
license     : MIT
subdir      : linux-64
url         : https://conda.anaconda.org/spyder-ide/linux-64/spyder-memory-profiler-0.2.1-py37hc8dfbb8_0.tar.bz2
md5         : bea8526a75cf90c77c72d1422be5ecbd
timestamp   : 2020-04-18 10:47:11 UTC
dependencies: 
  - memory_profiler
  - python >=3.7,<3.8.0a0
  - python_abi 3.7.* *_cp37m
  - spyder >=4,<5
```

Comparing with the previous conda package, the `python_abi` dependency is new, so I guess this is causing the problem. Any ideas what to do? @ccordoba12 @goanpeca

**Comment by jitseniesen** [comment]
Perhaps it is easier to build the conda package myself using `conda build` ?

**Comment by goanpeca** [comment]
Hmm we should probably remove any of those packages from spyder-ide

**Comment by ccordoba12** [comment]
> Comparing with the previous conda package, the python_abi dependency is new, so I guess this is causing the problem.

I think that means you can't install packages created by conda-forge in an environment that doesn't have a conda-forge Python, unless the package is `noarch`.

So my suggestion is to make the package `noarch` (since it doesn't have any dependency that is OS specific, that's possible), remove the previous version from our channel and upload the new packages again. That should work without issues.

**Comment by jitseniesen** [comment]
Thanks. I have removed the non-working packages from spyder-ide and I'll try using noarch.

**Comment by jitseniesen** [comment]
Yes, noarch did the trick! I should have thought of that myself ...

Thanks!

**Comment by ccordoba12** [comment]
No prob and glad my advice was helpful!
